stages:
  - draft
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main-v4"'
      variables:
        ENV: "migration"
    - if: '$CI_COMMIT_REF_NAME == "main"'
      variables:
        ENV: "prod"
    - if: '$CI_COMMIT_REF_NAME =~ /^migration\//'
      variables:
        ENV: "migration"
    - if: '$CI_COMMIT_REF_NAME =~ /^carte\//'
      variables:
        ENV: "test"

draft:
  stage: draft  
  tags:
    - SIG
  image: bitnami/git:latest
  before_script:
    - GIT_SSL_NO_VERIFY=true git fetch origin draft
  script:
    - git --version
    - echo $CI_COMMIT_SHA
    - echo $CI_COMMIT_BRANCH
    - echo $CI_COMMIT_MESSAGE
    - git checkout draft
    - git log -5 --oneline --graph --decorate
    - git merge remotes/origin/$CI_COMMIT_BRANCH
    - git remote set-url origin https://gitlab-ci:${MVIEWER_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - GIT_SSL_NO_VERIFY=true git push origin draft
   
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^carte\// && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: on_success

deploy-ansible:
  stage: deploy
  environment: ${ENV}
  tags:
    - SIG
    - deploy
  image: nexus.si.rennes.fr:5002/sig/ansible-runner:latest
  script:
    - ansible-galaxy collection install -r .deploy/requirements.yml
    - chmod 600 $GITLABRUNNERSIG_KEY
    - mkdir -p /root/.ssh
    - chmod 700 /root/.ssh
    - cp $GITLABRUNNERSIG_KEY /root/.ssh/GITLABRUNNERSIG_KEY
    - cp $ENV_FILE $CI_PROJECT_DIR/public/addons/env.json
    - |
      ansible-playbook \
        -i .deploy/inventory \
        .deploy/playbook.yml \
        --extra-vars \
          "CI_PROJECT_DIR=$CI_PROJECT_DIR \
            CI_PROJECT_NAME=$CI_PROJECT_NAME \
            MVIEWER_VERSION=$MVIEWER_VERSION \
            ENV=$ENV"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main-v4" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME =~ /^migration\// && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == "draft"'
      when: on_success
   
